language: python
python:
  - "2.7"
  - "3.3"
install:
  - pip install python-coveralls mock
  - sudo apt-get install -y rpm
script:
  - nosetests --with-coverage --cover-package=osclib --cover-inclusive
after_success:
  - coveralls
