before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y rpm
language: python
python:
  - "2.7"
  - "3.3"
install:
  - pip install coveralls
script:
  - coverage run --source=spec-cleaner make test
after_success:
  coveralls
